"""Rename 'justification' to 'remarks'

Revision ID: 301798f5ea13
Revises: 546c1e293edd
Create Date: 2025-04-28 20:07:29.568463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '301798f5ea13'
down_revision = '546c1e293edd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remarks', sa.String(length=255), nullable=True))
        batch_op.drop_column('justification')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('justification', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('remarks')

    # ### end Alembic commands ###
